title: Stackbit Vanilla Theme
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: A vanilla theme for Stackbit
header:
  title: Stackbit Vanilla
  has_nav: true
  nav_links:
    - label: Home
      url: /
    - label: Generic
      url: /generic/
    - label: Elements
      url: /elements/
    - label: Ipsum
      url: /ipsum/
footer:
  content: >-
    &copy; Stackbit. All rights reserved. This Jamstack site was created with <a
    href="https://www.stackbit.com/?utm_source=deployed-footer" target="_blank"
    rel="noopener">Stackbit</a>. Create yours <a
    href="https://app.stackbit.com/create?theme=vanilla&utm_source=deployed-footer"
    target="_blank" rel="noopener">now</a>
  has_social: true
  social_links:
    - label: Twitter
      url: 'https://twitter.com/'
      new_window: true
    - label: Instagram
      url: 'https://www.instagram.com/'
      new_window: true
    - label: GitHub
      url: 'https://github.com/'
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/'
      new_window: true
    - label: DEV
      url: 'https://dev.to/'
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
